In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.image as img
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
%matplotlib inline

1) Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [8]:
a=np.linspace(12,23,12)

In [9]:
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

2) Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [13]:
a1=np.reshape(a, (4,3))

In [14]:
a1

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [20]:
a2=np.reshape(a, (3,4))
a2

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [28]:
a3=np.reshape(a, (2,6))
a3

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [29]:
a4=np.reshape(a, (6,2))
a4

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [30]:
a5=np.reshape(a, (12,1))
a5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

In [44]:
b=np.linspace(12,38,27)
b

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37.,
       38.])

In [54]:
b1 = np.reshape(b, (3,3,3))
b1

array([[[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.]],

       [[21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]],

       [[30., 31., 32.],
        [33., 34., 35.],
        [36., 37., 38.]]])

3) Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [47]:
a11=np.reshape(a, (3,-1))
a11

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [48]:
a12=np.reshape(a, (2,-1))
a12

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [49]:
a13=np.reshape(a, (4,-1))
a13

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [50]:
a14=np.reshape(a, (-1,2))
a14

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [51]:
a14=np.reshape(a, (-1,1))
a14

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

4) Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?\
Ответ: Судя из проверки ранга через ndim можем сделать вывод, что матрица из 12 строк и одного столбца будет двумерной.

In [52]:
a14.ndim

2

In [53]:
a.ndim

1

In [55]:
b1.ndim

3

5) Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [135]:
c = np.random.randn(3, 4)
c

array([[-0.689591  , -0.81248787,  0.73552442, -0.45152276],
       [ 0.68192503, -0.85326766, -1.49321641, -2.24566794],
       [-1.0475014 ,  0.1185283 ,  1.59167067, -0.3308109 ]])

In [136]:
np.mean(c)

-0.39970146037767007

In [137]:
np.std(c)

1.0076115696460555

In [138]:
c0=c.flatten()
c0

array([-0.689591  , -0.81248787,  0.73552442, -0.45152276,  0.68192503,
       -0.85326766, -1.49321641, -2.24566794, -1.0475014 ,  0.1185283 ,
        1.59167067, -0.3308109 ])

6) Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [145]:
a=np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7) Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?\
Ответ: Разницы нет.


In [148]:
b=np.arange(20,1,-2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [149]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

8) Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [160]:
a=np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [162]:
b=np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [167]:
c=np.vstack((a,b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [168]:
c=np.concatenate((a,b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

9) Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [173]:
a = np.arange(0,12,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [174]:
A = np.reshape(a, (4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [176]:
A_t=A.T
A_t

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [180]:
B=A.dot(A_t)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [183]:
np.linalg.det(B)

0.0

10) Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [186]:
np.random.seed(42)

11) Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [187]:
c = np.arange(0,16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

12) Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [189]:
C = np.reshape(c, (4,4))
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [190]:
D=B+C*10
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [193]:
np.linalg.det(D)

5.18953807259442e-26

In [194]:
np.linalg.matrix_rank(D)

2

In [196]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66e+13, -1.49e+13, -1.10e+14,  7.83e+13],
       [ 1.63e+14, -3.81e+14,  2.72e+14, -5.45e+13],
       [-4.67e+14,  8.08e+14, -2.15e+14, -1.26e+14],
       [ 2.57e+14, -4.11e+14,  5.25e+13,  1.02e+14]])

13) Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [197]:
mask_positive = D_inv > 0
mask_negative = D_inv < 0

In [199]:
D_inv[mask_positive] = 1
D_inv[mask_negative] = 0
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [200]:
E = np.where(D_inv, B, C)
E

array([[  5,   1,   2,  32],
       [ 14,   5,  86,   7],
       [  8,  86,  10,  11],
       [ 32,  13, 212, 302]])